name: Release library module
on:
  push:
    branches:
      - main
jobs:
  publish-library:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout library repository
        uses: actions/checkout@v2
      - name: Bump up tag version
        id: bump_tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 1.0.0
      - name: Prepare for gradle command execution
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Execute gradle command to publish
        env:
          RELEASE_VERSION: ${{ steps.bump_tag_version.outputs.new_tag }}
          GITHUB_PACKAGE_USER_NAME: ryu1
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
